# Generated by Django 6.0.6 on 2026-07-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Nombre del apoderado que compra', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='student_name',
            field=models.CharField(blank=True, help_text='Nombre del niño/a (va en el diploma)', max_length=200),
        ),
    ]
