# Generated by Django 6.0.7 on 2026-09-13 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Lo que escribe el cliente al pagar. Ej: CYBER2026', max_length=30, unique=True)),
                ('description', models.CharField(blank=True, help_text='Nota interna para acordarse de para qué era. No la ve el cliente.', max_length=200)),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Porcentaje de descuento'), ('AMOUNT', 'Monto fijo en pesos')], default='PERCENT', max_length=10)),
                ('value', models.PositiveIntegerField(help_text='Si es porcentaje, de 1 a 100. Si es monto fijo, los pesos a descontar.')),
                ('min_purchase', models.PositiveIntegerField(default=0, help_text='Compra mínima para poder usarlo. 0 = sin mínimo.')),
                ('starts_at', models.DateTimeField(blank=True, help_text='Desde cuándo sirve. Vacío = desde ya.', null=True)),
                ('ends_at', models.DateTimeField(blank=True, help_text='Hasta cuándo sirve. Vacío = sin vencimiento.', null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Tope de compras que pueden usarlo. Vacío = sin tope.', null=True)),
                ('once_per_email', models.BooleanField(default=False, help_text='Cada correo puede usarlo una sola vez.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='payments.coupon'),
        ),
    ]
