# Generated by Django 6.0.7 on 2026-09-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_coupon_order_discount_amount_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('SHIPPING', 'Despacho a domicilio'), ('PICKUP', 'Retiro en tienda')], default='SHIPPING', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
