# Generated by Django 6.0.7 on 2026-09-30 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_product_es_suscripcion'),
        ('payments', '0006_order_delivery_method_order_picked_up_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarjetaOneclick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('username', models.CharField(max_length=40)),
                ('tbk_user', models.CharField(max_length=40)),
                ('tipo', models.CharField(blank=True, help_text='Visa, Mastercard, Redcompra…', max_length=30)),
                ('ultimos4', models.CharField(blank=True, max_length=4)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creada_en'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='pasarela',
            field=models.CharField(blank=True, choices=[('WEBPAY', 'Webpay Plus'), ('MERCADOPAGO', 'MercadoPago'), ('ONECLICK', 'Tarjeta (Transbank Oneclick)')], default='', max_length=12),
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('monto', models.PositiveIntegerField()),
                ('cada_meses', models.PositiveSmallIntegerField(default=1)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('CANCELADA', 'Cancelada'), ('SUSPENDIDA', 'Suspendida por cobros rechazados')], db_index=True, default='ACTIVA', max_length=12)),
                ('proximo_cobro', models.DateField(db_index=True)),
                ('intentos_fallidos', models.PositiveSmallIntegerField(default=0)),
                ('ultimo_error', models.CharField(blank=True, max_length=200)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('cancelada_en', models.DateTimeField(blank=True, null=True)),
                ('orden_inicial', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='suscripcion_iniciada', to='payments.order')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='catalog.product')),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='payments.tarjetaoneclick')),
            ],
            options={
                'ordering': ['-creada_en'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='suscripcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cobros', to='payments.suscripcion'),
        ),
    ]
