# Generated by Django 6.0.7 on 2026-09-30 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_tarjetaoneclick_order_pasarela_suscripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='origen',
            field=models.CharField(choices=[('TIENDA', 'Contratada en esta tienda'), ('WORDPRESS', 'Traída de WordPress')], db_index=True, default='TIENDA', max_length=10),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='wp_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='orden_inicial',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suscripcion_iniciada', to='payments.order'),
        ),
        migrations.AlterField(
            model_name='tarjetaoneclick',
            name='tbk_user',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
