# Generated by Django 6.0.7 on 2026-09-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_suscripciones_de_wordpress'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjustesCobros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cobros_automaticos', models.BooleanField(default=False)),
                ('cobrar_wordpress', models.BooleanField(default=False)),
                ('cambiado_por', models.CharField(blank=True, max_length=200)),
                ('cambiado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ajustes de cobros',
            },
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('PAUSADA', 'Pausada'), ('CANCELADA', 'Cancelada'), ('SUSPENDIDA', 'Suspendida por cobros rechazados')], db_index=True, default='ACTIVA', max_length=12),
        ),
    ]
