# Generated by Django 6.0.6 on 2026-07-02 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=200)),
                ('recipient_phone', models.CharField(max_length=30)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('region', models.CharField(max_length=120)),
                ('commune', models.CharField(max_length=120)),
                ('commune_id', models.IntegerField(blank=True, help_text='ID interno de Shipit', null=True)),
                ('address_street', models.CharField(max_length=255)),
                ('address_number', models.CharField(max_length=30)),
                ('address_detail', models.CharField(blank=True, help_text='Depto/oficina/referencia', max_length=255)),
                ('courier', models.CharField(max_length=80)),
                ('service_name', models.CharField(blank=True, max_length=120)),
                ('shipping_cost', models.IntegerField(default=0, help_text='CLP; se suma a Order.total_amount')),
                ('estimated_days', models.CharField(blank=True, max_length=120)),
                ('weight_kg', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('width_cm', models.DecimalField(decimal_places=2, default=10, max_digits=6)),
                ('height_cm', models.DecimalField(decimal_places=2, default=10, max_digits=6)),
                ('length_cm', models.DecimalField(decimal_places=2, default=10, max_digits=6)),
                ('shipit_reference', models.CharField(blank=True, max_length=120)),
                ('tracking_number', models.CharField(blank=True, max_length=120)),
                ('label_url', models.URLField(blank=True, help_text='PDF de la etiqueta', max_length=500)),
                ('status', models.CharField(choices=[('PENDING_DISPATCH', 'Pendiente de despacho'), ('CREATED', 'Envío creado (etiqueta generada)'), ('IN_TRANSIT', 'En tránsito'), ('DELIVERED', 'Entregado'), ('ERROR', 'Error al crear en Shipit')], default='PENDING_DISPATCH', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='payments.order')),
            ],
        ),
    ]
