# Generated by Django 6.0.7 on 2026-09-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoRetiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False, help_text='Si está apagado, el retiro en tienda no aparece en el checkout.')),
                ('nombre', models.CharField(default='Tienda Ingenio Blocks', help_text='Cómo se llama el lugar. Ej: Tienda Ingenio Blocks.', max_length=120)),
                ('direccion', models.CharField(blank=True, help_text='Calle y número. Ej: Av. Apoquindo 1234.', max_length=200)),
                ('comuna', models.CharField(default='Las Condes', max_length=120)),
                ('ciudad', models.CharField(default='Santiago', max_length=120)),
                ('referencia', models.CharField(blank=True, help_text='Cómo encontrarlo. Ej: Piso 2, local 15, frente al ascensor.', max_length=200)),
                ('horario', models.TextField(blank=True, help_text='Cuándo se puede ir a retirar. Ej: Lunes a viernes de 10:00 a 18:00.')),
                ('instrucciones', models.TextField(blank=True, help_text='Qué tiene que hacer o llevar la persona. Ej: presenta tu número de pedido.')),
                ('mapa_url', models.URLField(blank=True, help_text='Link a Google Maps, opcional. Aparece como botón "Ver en el mapa".', max_length=500)),
            ],
            options={
                'verbose_name': 'Punto de retiro',
                'verbose_name_plural': 'Punto de retiro',
            },
        ),
    ]
