# Generated by Django 6.0.7 on 2026-09-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_puntoretiro'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjustesEnvios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enviar_a_shipit_al_pagar', models.BooleanField(default=True)),
                ('cambiado_por', models.CharField(blank=True, max_length=200)),
                ('cambiado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ajustes de envíos',
            },
        ),
        migrations.AddField(
            model_name='shipment',
            name='courier_code',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='shipment',
            name='error_shipit',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
