# Generated by Django 6.0.7 on 2026-09-30 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_shipit_automatico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajustesenvios',
            name='enviar_a_shipit_al_pagar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('PENDING_DISPATCH', 'Pendiente de despacho'), ('CREATED', 'En Shipit (Ventas)'), ('IN_TRANSIT', 'En tránsito'), ('DELIVERED', 'Entregado'), ('ERROR', 'Error al crear en Shipit')], default='PENDING_DISPATCH', max_length=20),
        ),
    ]
