# Generated by Django 6.0.7 on 2026-09-26 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BajaDeCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('categoria', models.CharField(choices=[('novedades', 'Novedades'), ('aula', 'Avisos del Aula')], max_length=20)),
                ('origen', models.CharField(blank=True, choices=[('enlace', 'Desde el enlace del correo'), ('un_clic', 'Con el botón de baja de su correo'), ('cuenta', 'Desde su cuenta')], max_length=20)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'baja de correo',
                'verbose_name_plural': 'bajas de correo',
                'ordering': ['-creada_en'],
                'unique_together': {('email', 'categoria')},
            },
        ),
        migrations.CreateModel(
            name='EnvioMasivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=150)),
                ('cuerpo', models.TextField(help_text='Separa los párrafos con una línea en blanco. Las direcciones web se vuelven enlaces solas.')),
                ('boton_texto', models.CharField(blank=True, help_text='Opcional. Ej: "Conoce la nueva página".', max_length=40, verbose_name='Texto del botón')),
                ('boton_url', models.URLField(blank=True, help_text='A dónde lleva el botón. Tiene que empezar con https://', verbose_name='Dirección del botón')),
                ('audiencia', models.CharField(choices=[('TODOS', 'Todos los clientes'), ('VIGENTES', 'Solo con membresía vigente')], default='TODOS', max_length=10)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_COLA', 'Enviándose'), ('TERMINADO', 'Enviado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('prueba_enviada_en', models.DateTimeField(blank=True, null=True)),
                ('prueba_huella', models.CharField(blank=True, max_length=64)),
                ('encolado_en', models.DateTimeField(blank=True, null=True)),
                ('terminado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios_masivos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'correo masivo',
                'verbose_name_plural': 'correos masivos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='DestinatarioMasivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIANDO', 'Enviándose'), ('ENVIADO', 'Enviado'), ('FALLIDO', 'Falló'), ('OMITIDO', 'Omitido (se dio de baja)')], default='PENDIENTE', max_length=10)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='comunicaciones.enviomasivo')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('envio', 'email')},
            },
        ),
    ]
