# Generated by Django 6.0.7 on 2026-09-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviomasivo',
            name='cuerpo_html',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='enviomasivo',
            name='cuerpo',
            field=models.TextField(blank=True),
        ),
    ]
