# Generated by Django 6.0.7 on 2026-09-30 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicaciones', '0002_cuerpo_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviomasivo',
            name='audiencia',
            field=models.CharField(choices=[('PRUEBA', 'Prueba: solo a los administradores'), ('TODOS', 'Todos los clientes'), ('VIGENTES', 'Solo con membresía vigente')], default='PRUEBA', max_length=10),
        ),
    ]
