# Generated by Django 6.0.7 on 2026-08-09 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrigenDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('origen', models.CharField(help_text='Dominio de procedencia, o "directo"', max_length=120)),
                ('visitas', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'origen diario',
                'verbose_name_plural': 'orígenes diarios',
                'ordering': ['-fecha'],
                'unique_together': {('fecha', 'origen')},
            },
        ),
        migrations.CreateModel(
            name='VisitaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('ruta', models.CharField(help_text='Ej: / o /checkout', max_length=200)),
                ('vistas', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'visita diaria',
                'verbose_name_plural': 'visitas diarias',
                'ordering': ['-fecha'],
                'unique_together': {('fecha', 'ruta')},
            },
        ),
        migrations.CreateModel(
            name='VisitanteDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('huella', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'visitante diario',
                'verbose_name_plural': 'visitantes diarios',
                'ordering': ['-fecha'],
                'unique_together': {('fecha', 'huella')},
            },
        ),
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, help_text='Copia del correo usado, sobrevive al borrado de la cuenta', max_length=254)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entró'), ('FALLIDO', 'Intento fallido'), ('SALIDA', 'Cerró sesión')], db_index=True, max_length=10)),
                ('zona', models.CharField(choices=[('PANEL', 'Panel de gestión'), ('SITIO', 'Aula Virtual')], db_index=True, max_length=10)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('dispositivo', models.CharField(blank=True, help_text='Navegador y sistema, resumido', max_length=200)),
                ('momento', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de acceso',
                'verbose_name_plural': 'registros de acceso',
                'ordering': ['-momento'],
                'indexes': [models.Index(fields=['zona', '-momento'], name='panel_regis_zona_e2b2a9_idx')],
            },
        ),
    ]
