# Generated by Django 6.0.6 on 2026-07-02 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dte_type', models.IntegerField(default=39, help_text='Tipo de DTE (39 = boleta electrónica)')),
                ('folio', models.CharField(blank=True, help_text='Folio asignado por el SII/OpenFactura', max_length=40)),
                ('token', models.CharField(blank=True, help_text='Token del documento en OpenFactura', max_length=120)),
                ('pdf_base64', models.TextField(blank=True, help_text='PDF de la boleta en base64 (descargable desde el admin)')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de emisión'), ('ISSUED', 'Emitida'), ('ERROR', 'Error al emitir')], default='PENDING', max_length=12)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='payments.order')),
            ],
        ),
    ]
