# Generated by Django 6.0.6 on 2026-07-15 23:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def backfill_course_order(apps, schema_editor):
    """Los cursos que ya existían no tenían orden explícito; les asignamos uno
    secuencial según su fecha de creación (el orden implícito que tenían antes)."""
    Course = apps.get_model('lms', 'Course')
    for i, course in enumerate(Course.objects.order_by('created_at', 'id'), start=1):
        course.order = i
        course.save(update_fields=['order'])


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_alter_lesson_pdf_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='course',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Posición en la secuencia semanal (1 = primero). Se arrastra en el panel.'),
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='lms.course')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to='lms.membership')),
            ],
            options={
                'unique_together': {('membership', 'course')},
            },
        ),
        migrations.RunPython(backfill_course_order, migrations.RunPython.noop),
    ]
