# Generated by Django 6.0.6 on 2026-07-16 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_alter_course_options_course_order_courseprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='parent_name',
            field=models.CharField(blank=True, help_text='Nombre del padre/apoderado', max_length=200),
        ),
        migrations.AddField(
            model_name='membership',
            name='paused_at',
            field=models.DateTimeField(blank=True, help_text='Si está pausada, desde cuándo', null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='student_name',
            field=models.CharField(blank=True, help_text='Nombre del alumno (niño/a)', max_length=200),
        ),
        migrations.AddField(
            model_name='membership',
            name='total_paused_days',
            field=models.PositiveIntegerField(default=0, help_text='Días acumulados en pausa (se usan para correr las fechas al reanudar)'),
        ),
    ]
