# Generated by Django 6.0.6 on 2026-07-16 09:18

import django.core.files.storage
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_membership_parent_name_membership_paused_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Ej: 'Diploma Nivel Básico'", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Mensaje que aparece en el diploma')),
                ('image_url', models.URLField(blank=True, help_text='Imagen/fondo del diploma (opcional). Si se deja vacío se usa el diseño por defecto de IngenioBlocks.', max_length=500)),
                ('order', models.PositiveIntegerField(default=0, help_text='Posición en la secuencia (compartida con los cursos)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, help_text='Texto que acompaña al recurso (paso a paso, instrucciones)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='image_file',
            field=models.FileField(blank=True, help_text='Imagen protegida (paso a paso). Solo para recursos de tipo IMAGE.', null=True, storage=lms.models.protected_storage, upload_to='lesson_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('VIDEO', 'Video'), ('PDF', 'Documento PDF'), ('IMAGE', 'Imagen')], max_length=5),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Orden del recurso dentro del curso'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='PDF protegido. Solo para recursos de tipo PDF.', null=True, storage=lms.models.protected_storage, upload_to='lessons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_embed_url',
            field=models.URLField(blank=True, help_text='URL de embed del video (YouTube/Vimeo). Solo para recursos de tipo VIDEO.', max_length=500),
        ),
        migrations.CreateModel(
            name='DiplomaAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('diploma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='lms.diploma')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diploma_awards', to='lms.membership')),
            ],
            options={
                'unique_together': {('membership', 'diploma')},
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='lms.lesson')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='lms.membership')),
            ],
            options={
                'unique_together': {('membership', 'lesson')},
            },
        ),
    ]
