# Generated by Django 6.0.6 on 2026-07-22 15:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_diploma_lesson_description_lesson_image_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diplomaaward',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UnlockNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlock_notices', to='lms.course')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlock_notices', to='lms.membership')),
            ],
            options={
                'unique_together': {('membership', 'course')},
            },
        ),
    ]
