# Generated by Django 6.0.6 on 2026-07-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_diplomaaward_email_sent_at_unlocknotice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjustesAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursos_iniciales', models.PositiveIntegerField(default=3, help_text='Cuántos modelos quedan disponibles apenas se compra. Del siguiente en adelante se libera uno por semana.')),
                ('bloqueados_visibles', models.PositiveIntegerField(default=1, help_text='Cuántos modelos bloqueados se muestran después de los disponibles, para dar a entender que viene más. 0 = mostrarlos todos.')),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ajustes del Aula Virtual',
                'verbose_name_plural': 'Ajustes del Aula Virtual',
            },
        ),
    ]
