# Generated by Django 6.0.6 on 2026-07-25 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_ajustesaula'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image_file',
            field=models.FileField(blank=True, help_text='JPG, PNG o WEBP. Ideal horizontal (16:9). Si la subes acá, manda sobre la URL.', upload_to='cursos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Imagen de portada'),
        ),
        migrations.AddField(
            model_name='diploma',
            name='image_file',
            field=models.FileField(blank=True, help_text='Opcional (JPG, PNG o WEBP). Si no subes nada se usa el diseño por defecto.', upload_to='diplomas/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Imagen del diploma'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image_url',
            field=models.URLField(blank=True, help_text='Alternativa: dirección de una imagen ya publicada en internet.', max_length=500),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='image_url',
            field=models.URLField(blank=True, help_text='Alternativa: dirección de una imagen ya publicada en internet.', max_length=500),
        ),
    ]
