# Generated by Django 6.0.7 on 2026-08-14 12:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_course_image_file_diploma_image_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('modo', models.CharField(choices=[('GOTEO', 'Goteo semanal'), ('TODO', 'Todo desbloqueado de una')], default='GOTEO', help_text='Goteo: se libera un modelo por semana. Todo: quedan todos disponibles apenas se compra.', max_length=10)),
                ('cursos_iniciales', models.PositiveIntegerField(default=3, help_text='Solo en modo goteo: cuántos modelos quedan disponibles apenas se compra. Del siguiente en adelante se libera uno por semana.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'categoría de cursos',
                'verbose_name_plural': 'categorías de cursos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='diploma',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Se gana al completar todos los cursos de esta categoría.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diplomas', to='lms.coursecategory', verbose_name='Categoría'),
        ),
        migrations.CreateModel(
            name='MembershipCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtenida_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias_con_categoria', to='lms.coursecategory')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_obtenidas', to='lms.membership')),
            ],
            options={
                'verbose_name': 'categoría del alumno',
                'verbose_name_plural': 'categorías del alumno',
                'unique_together': {('membership', 'categoria')},
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='membresias', through='lms.MembershipCategory', to='lms.coursecategory'),
        ),
        migrations.CreateModel(
            name='CategoryCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Posición dentro de esta categoría (1 = primero).')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_del_curso', to='lms.course')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_en_categoria', to='lms.coursecategory')),
            ],
            options={
                'verbose_name': 'curso de la categoría',
                'verbose_name_plural': 'cursos de la categoría',
                'ordering': ['orden', 'id'],
                'unique_together': {('categoria', 'curso')},
            },
        ),
    ]
