# Generated by Django 6.0.7 on 2026-08-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_migrar_a_categoria_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajustesaula',
            name='acceso_vencido',
            field=models.CharField(choices=[('CARATULAS', 'Ve las carátulas pero no puede entrar'), ('TODO', 'Sigue viendo todo, como si no se hubiera vencido'), ('NADA', 'No ve nada hasta que renueve')], default='CARATULAS', help_text='Dejarle las carátulas a la vista le recuerda lo que se está perdiendo; esconderlo todo hace que el Aula se vea vacía.', max_length=10, verbose_name='Cuando se le vence la suscripción'),
        ),
        migrations.AddField(
            model_name='ajustesaula',
            name='diplomas_tras_vencer',
            field=models.BooleanField(default=True, help_text='Un diploma ganado es del alumno. Bloquearlo genera reclamos de quien ya lo tenía y no cambia si renueva o no.', verbose_name='Los diplomas ya ganados se siguen pudiendo descargar'),
        ),
        migrations.AddField(
            model_name='ajustesaula',
            name='reanudar_goteo',
            field=models.BooleanField(default=True, help_text='Se le abren de inmediato los primeros modelos de cada categoría contando desde el último que terminó, y de ahí sigue uno por semana. Si lo apagas, al renovar se le abre de golpe todo lo que el calendario había liberado mientras estuvo vencido.', verbose_name='Al renovar, el goteo empieza de nuevo desde donde quedó'),
        ),
        migrations.AddField(
            model_name='membershipcategory',
            name='entregados_al_reanudar',
            field=models.PositiveIntegerField(default=0, help_text='Cuántos modelos de esta categoría ya tenía terminados al reanudar. Esos siguen abiertos; el goteo continúa desde el siguiente.'),
        ),
        migrations.AddField(
            model_name='membershipcategory',
            name='pausa_al_reanudar',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='membershipcategory',
            name='reanudada_en',
            field=models.DateTimeField(blank=True, help_text='Si renovó después de vencerse, desde cuándo corre su calendario ahora.', null=True),
        ),
    ]
