# Generated by Django 6.0.7 on 2026-08-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_ajustesaula_acceso_vencido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajustesaula',
            name='acceso_vencido',
            field=models.CharField(choices=[('CARATULAS', 'Puede repasar los modelos que terminó, el resto queda cerrado'), ('TODO', 'Sigue viendo todo, como si no se hubiera vencido'), ('NADA', 'No ve nada hasta que renueve')], default='CARATULAS', help_text='Lo que ya terminó lo pagó y volver a armarlo es lo que más se hace en ese estado; lo que le falta es justamente lo que compra al renovar. Esconderlo todo hace que el Aula se vea vacía.', max_length=10, verbose_name='Cuando se le vence la suscripción'),
        ),
    ]
