# Generated by Django 6.0.7 on 2026-08-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0013_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='es_legado',
            field=models.BooleanField(default=False, help_text='Cuenta migrada del WordPress viejo'),
        ),
    ]
