# Generated by Django 6.0.7 on 2026-09-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0014_membership_es_legado'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='trailer_url',
            field=models.CharField(blank=True, help_text='Video corto de MARKETING que se ve en la portada, no el paso a paso. Pega el link tal cual. Si lo dejas vacío, en la portada la tarjeta muestra solo la foto.', max_length=300, verbose_name='Trailer de YouTube'),
        ),
    ]
