# Generated by Django 6.0.7 on 2026-09-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0016_rescatar_trailers'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='mostrar_en_portada',
            field=models.BooleanField(default=True, help_text='Aparece entre los modelos de la portada. Apágalo para lo que no sea un modelo armable (la bienvenida, una introducción): el alumno lo sigue recibiendo igual en el Aula.', verbose_name='Mostrar en la portada'),
        ),
    ]
