# Generated by Django 6.0.7 on 2026-09-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0017_course_mostrar_en_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='mostrar_en_portada',
            field=models.BooleanField(default=True, help_text='Aparece entre los modelos de la portada, si además tiene trailer. Apágalo para lo que no sea un modelo armable (la bienvenida, una introducción): el alumno lo sigue recibiendo igual en el Aula.', verbose_name='Mostrar en la portada'),
        ),
        migrations.AlterField(
            model_name='course',
            name='trailer_url',
            field=models.CharField(blank=True, help_text='Video corto de MARKETING que se ve en la portada, no el paso a paso. Pega el link tal cual. Sin trailer el modelo NO aparece en la portada: esa galería es para ver los videos.', max_length=300, verbose_name='Trailer de YouTube'),
        ),
    ]
