# Generated by Django 6.0.7 on 2026-09-15 15:27

import django.core.validators
import lms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0018_alter_course_mostrar_en_portada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, help_text="Video protegido, para clips propios. Los videos largos van a YouTube como 'no listado' y se pegan en el campo de arriba.", null=True, storage=lms.models.protected_storage, upload_to='lesson_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov', 'm4v'])]),
        ),
    ]
