# Generated by Django 6.0.7 on 2026-09-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0019_lesson_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='phone',
            field=models.CharField(blank=True, help_text='Teléfono de contacto', max_length=30),
        ),
    ]
