# Generated by Django 6.0.7 on 2026-09-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0021_telefonos_desde_las_compras'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='sin_vencimiento',
            field=models.BooleanField(default=False, help_text='La membresía no caduca: se mantiene activa hasta que se dé de baja. Se apaga sola con el próximo pago.', verbose_name='Sin fecha de vencimiento'),
        ),
    ]
