# Generated by Django 6.0.7 on 2026-09-24 16:19

from django.db import migrations, models


def marcar_la_bienvenida(apps, schema_editor):
    """La bienvenida no es un desafío: es la introducción al Aula.

    Se apaga sola en vez de dejarlo a mano porque el campo nace en True y
    nadie iba a acordarse; el certificado habría dicho 13 donde van 12.
    Se busca por el título, que es lo único que la distingue, y el panel
    permite corregirlo si algún día se llama de otra forma.
    """
    Course = apps.get_model('lms', 'Course')
    Course.objects.filter(title__icontains='bienvenida').update(cuenta_como_desafio=False)


def volver_a_contarla(apps, schema_editor):
    Course = apps.get_model('lms', 'Course')
    Course.objects.filter(title__icontains='bienvenida').update(cuenta_como_desafio=True)


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0022_membership_sin_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cuenta_como_desafio',
            field=models.BooleanField(default=True, help_text='Apágalo para lo que no sea un modelo armable (la bienvenida, una introducción). Esos no se suman a la cantidad de desafíos que dice el certificado.', verbose_name='Cuenta como desafío'),
        ),
        migrations.RunPython(marcar_la_bienvenida, volver_a_contarla),
    ]
