# Generated by Django 6.0.6 on 2026-06-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height_cm',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Alto en CM', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='length_cm',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Largo en CM', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Peso en KG', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='width_cm',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Ancho en CM', max_digits=5),
        ),
    ]
