# Generated by Django 6.0.6 on 2026-07-02 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_height_cm_product_length_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='access_months',
            field=models.PositiveIntegerField(default=12, help_text='Meses de acceso al LMS incluidos al comprar este producto'),
        ),
    ]
