# Generated by Django 6.0.6 on 2026-07-02 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_access_months'),
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='courses',
            field=models.ManyToManyField(blank=True, help_text='Cursos a los que da acceso la compra de este producto', related_name='products', to='lms.course'),
        ),
    ]
