# Generated by Django 6.0.6 on 2026-07-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, default='', help_text='Beneficios de la tarjeta, uno por línea'),
        ),
        migrations.AddField(
            model_name='product',
            name='highlight',
            field=models.BooleanField(default=False, help_text='Destacar esta tarjeta con el estilo morado'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_coming_soon',
            field=models.BooleanField(default=False, help_text="Marcar como 'Próximamente': se muestra pero no se puede comprar aún"),
        ),
        migrations.AddField(
            model_name='product',
            name='is_on_sale',
            field=models.BooleanField(default=False, help_text='Mostrar el producto en oferta (ribbon rojo)'),
        ),
        migrations.AddField(
            model_name='product',
            name='landing_badge',
            field=models.CharField(blank=True, default='', help_text="Etiqueta de la tarjeta, ej: 'pago único' o 'pago mensual'", max_length=40),
        ),
        migrations.AddField(
            model_name='product',
            name='landing_order',
            field=models.PositiveIntegerField(default=0, help_text='Orden en la portada. Los 3 primeros van en tarjetas; el 4º va en la tarjeta ancha de abajo'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_note',
            field=models.CharField(blank=True, default='', help_text="Nota junto al precio, ej: '/ pago único'", max_length=40),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Precio de oferta en CLP (se cobra este si el producto está en oferta)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='show_on_landing',
            field=models.BooleanField(default=False, help_text='Mostrar este producto en la sección de kits de la portada (máximo 4)'),
        ),
    ]
