# Generated by Django 6.0.6 on 2026-07-18 20:37

from django.db import migrations


def seed_faqs(apps, schema_editor):
    """Crea las 6 preguntas frecuentes originales (las que ya estaban fijas
    en la landing) solo si la tabla está vacía, para no duplicar si esta
    migración corre más de una vez en un mismo entorno."""
    FAQ = apps.get_model('catalog', 'FAQ')
    if FAQ.objects.exists():
        return
    from catalog.models import DEFAULT_FAQS
    FAQ.objects.bulk_create([
        FAQ(question=f['question'], answer=f['answer'], order=i)
        for i, f in enumerate(DEFAULT_FAQS, start=1)
    ])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_faq'),
    ]

    operations = [
        migrations.RunPython(seed_faqs, noop),
    ]
