# Generated by Django 6.0.6 on 2026-07-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_seed_default_faqs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('quote', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Estrellas, de 1 a 5')),
                ('order', models.PositiveIntegerField(default=0, help_text='Posición en la lista. Se asigna solo al crear.')),
                ('is_active', models.BooleanField(default=True, help_text='Se muestra en la landing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
                'ordering': ['order', 'id'],
            },
        ),
    ]
