# Generated by Django 6.0.6 on 2026-07-18 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_seed_default_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='requires_login',
            field=models.BooleanField(default=False, help_text='Solo se puede comprar con la sesión iniciada (para packs de modelos o planes que requieren haber comprado antes el kit con las piezas)'),
        ),
    ]
