# Generated by Django 6.0.6 on 2026-07-20 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_product_requires_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('youtube_url', models.CharField(help_text='Pega el link de YouTube tal cual (youtube.com/watch?v=…, youtu.be/… o el ID)', max_length=300)),
                ('cover', models.FileField(blank=True, help_text='Imagen de portada del video (JPG, PNG o WEBP). Ideal horizontal, 16:9.', upload_to='landing_videos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('order', models.PositiveIntegerField(default=0, help_text='Posición en la lista. Se asigna solo al crear.')),
                ('is_active', models.BooleanField(default=True, help_text='Se muestra en la landing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video de la portada',
                'verbose_name_plural': 'Videos de la portada',
                'ordering': ['order', 'id'],
            },
        ),
    ]
