# Generated by Django 6.0.6 on 2026-07-20 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_seed_landing_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('photo', models.FileField(blank=True, help_text='Foto del paso (JPG, PNG o WEBP). Ideal horizontal.', upload_to='landing_steps/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('color', models.CharField(choices=[('#6a3093', 'Morado'), ('#00a63e', 'Verde'), ('#ff6101', 'Naranjo'), ('#8200db', 'Morado brillante'), ('#ffcb00', 'Amarillo')], default='#6a3093', max_length=7)),
                ('icon', models.CharField(choices=[('kit', 'Carrito de compras'), ('aula', 'Pantalla / Aula virtual'), ('juega', 'Mando de videojuego')], default='kit', max_length=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='Posición en la lista. Se asigna solo al crear.')),
                ('is_active', models.BooleanField(default=True, help_text='Se muestra en la landing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paso de "Cómo funciona"',
                'verbose_name_plural': 'Pasos de "Cómo funciona"',
                'ordering': ['order', 'id'],
            },
        ),
    ]
