# Generated by Django 6.0.6 on 2026-07-26 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_seed_landing_steps'),
    ]

    operations = [
        migrations.CreateModel(
            name='GanadorConcurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(help_text='Ej: 6 a 8 años. Aparece en el pie de la lámina.', max_length=60, verbose_name='Categoría')),
                ('tono', models.CharField(choices=[('amarillo', 'Amarillo'), ('morado', 'Morado')], default='amarillo', max_length=10, verbose_name='Color de la lámina')),
                ('titulo', models.CharField(default='Ganador', help_text='"Ganador" o "Ganadora", según corresponda.', max_length=40, verbose_name='Título')),
                ('anio', models.CharField(blank=True, max_length=10, verbose_name='Año')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('edad', models.CharField(blank=True, max_length=40, verbose_name='Edad')),
                ('texto', models.TextField(blank=True, help_text='Un par de líneas sobre el modelo ganador.', verbose_name='Reseña')),
                ('foto', models.FileField(blank=True, help_text='Foto del ganador o de su modelo (JPG, PNG o WEBP). Se recorta cuadrada.', upload_to='ganadores/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Foto')),
                ('order', models.PositiveIntegerField(default=0, help_text='Posición en la lista. Se asigna solo al crear.')),
                ('is_active', models.BooleanField(default=True, help_text='Se muestra en la landing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ganador del concurso',
                'verbose_name_plural': 'Ganadores del concurso',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SeccionConcurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('oculta', 'Oculta — la sección no aparece en la portada'), ('convocatoria', 'Convocatoria — invita a participar en el concurso'), ('ganadores', 'Ganadores — muestra quiénes ganaron')], default='oculta', max_length=20, verbose_name='Qué se muestra')),
                ('etiqueta', models.CharField(default='Concurso Ingenio Blocks', help_text='El rótulo lila chico que va sobre el título.', max_length=80, verbose_name='Etiqueta')),
                ('titulo', models.CharField(default='Despierta tu ingenio creativo', max_length=140, verbose_name='Título')),
                ('intro', models.CharField(default='Para participar deberás:', help_text='La línea en negrita que encabeza la lista de requisitos.', max_length=200, verbose_name='Frase de entrada')),
                ('bases', models.TextField(default='Enviar 3 fotografías de tu modelo (en buena resolución) desde distintos ángulos.\nUn video con el modelo funcionando.\nEnviar las fotografías y video a nuestro correo: contacto@ingenioblocks.com indicando en el asunto: Concurso Ingenio Blocks\nEl correo, además, deberá indicar el nombre o pseudónimo del niñ@ y el nombre del modelo. Nombre y teléfono de uno de los padres o apoderado.', help_text='Uno por línea. Cada línea se muestra como una viñeta. Los correos y los links se vuelven clickeables solos.', verbose_name='Requisitos')),
                ('boton_texto', models.CharField(default='¡Envía tu modelo ahora!', max_length=60, verbose_name='Texto del botón')),
                ('boton_enlace', models.CharField(blank=True, default='mailto:contacto@ingenioblocks.com?subject=Concurso%20Ingenio%20Blocks', help_text='Puede ser una dirección web (https://…) o un correo (mailto:alguien@ingenioblocks.com). Si se deja vacío, el botón no aparece.', max_length=300, verbose_name='Enlace del botón')),
                ('sello', models.CharField(blank=True, default='¡Participa y gana!', help_text='El texto del círculo morado de la esquina. Vacío = sin sello.', max_length=40, verbose_name='Sello')),
                ('imagen', models.FileField(blank=True, help_text='La foto del modelo que acompaña a la convocatoria (JPG, PNG o WEBP).', upload_to='concurso/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Imagen')),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sección del concurso',
                'verbose_name_plural': 'Sección del concurso',
            },
        ),
    ]
