# Generated by Django 6.0.6 on 2026-08-07 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_ganadorconcurso_seccionconcurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ganadorconcurso',
            name='foto',
            field=models.FileField(blank=True, help_text='Foto del ganador o de su modelo (JPG, PNG o WEBP). Se recorta cuadrada, mínimo 500×500 px.', upload_to='ganadores/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='landingstep',
            name='photo',
            field=models.FileField(blank=True, help_text='JPG, PNG o WEBP. Horizontal, proporción 1.6:1 aprox., mínimo 800×495 px.', upload_to='landing_steps/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='landingvideo',
            name='cover',
            field=models.FileField(blank=True, help_text='JPG, PNG o WEBP. Horizontal 16:9, mínimo 800×450 px.', upload_to='landing_videos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='seccionconcurso',
            name='imagen',
            field=models.FileField(blank=True, help_text='La foto del modelo que acompaña a la convocatoria (JPG, PNG o WEBP). No se recorta, se muestra completa. Mínimo 700 px de ancho.', upload_to='concurso/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Imagen'),
        ),
    ]
