# Generated by Django 6.0.7 on 2026-08-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_help_text_resoluciones_imagenes'),
        ('lms', '0009_categorias_de_cursos'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Todo lo que esté en estas categorías queda incluido, ahora y cuando se agreguen modelos nuevos.', related_name='products', to='lms.coursecategory', verbose_name='Categorías que incluye'),
        ),
        migrations.AlterField(
            model_name='product',
            name='courses',
            field=models.ManyToManyField(blank=True, help_text='Cursos sueltos a los que da acceso (heredado). Lo normal es usar las categorías: los cursos nuevos de esa categoría llegan solos, sin tener que volver acá.', related_name='products', to='lms.course'),
        ),
    ]
