# Generated by Django 6.0.7 on 2026-08-16 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_categorias_de_cursos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloArmable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140, verbose_name='Nombre del modelo')),
                ('descripcion', models.TextField(blank=True, help_text='Una o dos líneas sobre qué hace o qué se aprende. Opcional.', verbose_name='Descripción')),
                ('youtube_url', models.CharField(blank=True, help_text='Pega el link tal cual (youtube.com/watch?v=…, youtu.be/… o el ID). Si lo dejas vacío, la tarjeta muestra solo la foto.', max_length=300, verbose_name='Trailer de YouTube')),
                ('foto', models.FileField(blank=True, help_text='JPG, PNG o WEBP. Horizontal 16:9, mínimo 800×450 px. Si no subes ninguna, se usa la miniatura del trailer.', upload_to='modelos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Foto del modelo')),
                ('order', models.PositiveIntegerField(default=0, help_text='Posición en la página. Se arrastra en el panel.')),
                ('is_active', models.BooleanField(default=True, help_text='Se muestra en la página')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modelo de la vitrina',
                'verbose_name_plural': 'Modelos de la vitrina',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SeccionModelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True, help_text='Si lo apagas, la página deja de aparecer en el menú y de abrirse. Los modelos que hayas cargado se conservan.', verbose_name='Mostrar la página de modelos')),
                ('titulo', models.CharField(default='Todo lo que se puede armar', max_length=140, verbose_name='Título de la página')),
                ('intro', models.TextField(blank=True, default='Cada semana se abre un modelo nuevo en el Aula Virtual. Estos son todos los que vienen.', verbose_name='Texto de entrada')),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Página de modelos',
                'verbose_name_plural': 'Página de modelos',
            },
        ),
    ]
