# Generated by Django 6.0.7 on 2026-09-11 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_modeloarmable_seccionmodelos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModeloArmable',
        ),
        migrations.DeleteModel(
            name='SeccionModelos',
        ),
    ]
