# Generated by Django 6.0.7 on 2026-09-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_delete_modeloarmable_delete_seccionmodelos'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='exento_iva',
            field=models.BooleanField(default=True, help_text='La boleta lo muestra como "producto o servicio exento o no afecto" y no le suma IVA. Desmárcalo solo si este producto sí paga IVA.', verbose_name='Exento de IVA'),
        ),
    ]
