# Generated by Django 6.0.7 on 2026-09-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_product_exento_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='acepta_cupones',
            field=models.BooleanField(default=True, help_text='Si se apaga, los cupones no le descuentan nada a este producto'),
        ),
    ]
