# Generated by Django 6.0.7 on 2026-09-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_product_acepta_cupones'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='es_suscripcion',
            field=models.BooleanField(default=False, help_text="Se cobra automáticamente cada 'Meses de acceso' meses con la tarjeta del cliente"),
        ),
    ]
